ignorePaths:
  - "@AH-64D Apache Longbow/Addons/fza_ah64_model" # fza_ah64_model is non-compliant with the ideal structure - requires long-term work
  - "@AH-64D Apache Longbow/Addons/fza_ah64_controls/font" # Fonts require specific filename structrures
  - "@AH-64D Apache Longbow/Addons/fza_ah64_mpd/tex/tsdIcons" # Icons have a specific filename structure
  - "@AH-64D Apache Longbow/Addons/fza_ah64_mpd/font/BMKApacheFont" # Icons have a specific filename structure
  - "@AH-64D Apache Longbow/Addons/fza_ah64_mpd/font/BMKApacheFontTextures" # Icons have a specific filename structure
  - "@AH-64D Apache Longbow/Addons/fza_ah64_cannon/data"
  - "@AH-64D Apache Longbow/Addons/fza_ah64_controls/data"
  - "@AH-64D Apache Longbow/Addons/fza_ah64_hydra/data"
  - "@AH-64D Apache Longbow/Addons/fza_ah64_hellfire/data"
  - "@AH-64D Apache Longbow/Addons/fza_ah64_ase/data"
  - "@AH-64D Apache Longbow/Addons/fza_ah64_hatchet/components/Gunner"
  - "@AH-64D Apache Longbow/Addons/fza_ah64_hatchet/components/Pilot"
ignoreFileNames:
  - "$PBOPREFIX$"
  - "$PREFIX$"
  - "BIS_AddonInfo.hpp"
  - "XEH_preInit.sqf"
  - "UserActionGroups.hpp"
  - "UserActionsConflictGroups.hpp"
  - "ACE_GuidanceConfig.hpp"
  - ".gitignore"
